services:
  moderator:
    image: moderator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
      - PORT=4002
      - SUBMIT_SERVICE_URL=https://submit-service.ddns.net
      - DELIVER_SERVICE_URL=https://deliver-service.duckdns.org
    networks:
      - joke-network

networks:
  joke-network:
    driver: bridge
