services:
  moderator:
    image: moderator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
      - PORT=4002
      - SUBMIT_SERVICE_URL=http://20.6.129.109:4001
      - DELIVER_SERVICE_URL=http://20.2.80.201:4003
    networks:
      - joke-network

networks:
  joke-network:
    driver: bridge
