// login request 

POST /auth/login HTTP/1.1
Host: localhost:4002
Content-Type: application/json
Content-Length: 36

{
    "email": "admin@admin.com",
    "password": "admin123"
}

###

GET /moderator/jokes HTTP/1.1
Host: localhost:4002
Content-Type: application/json

### 
POST /moderator/category HTTP/1.1
Host: localhost:4002
Content-Type: application/json

{
  "category": "New"
}

###
GET /moderator/category HTTP/1.1
Host: localhost:4002
Content-Type: application/json

### 
PATCH /moderator/jokes HTTP/1.1
Host: localhost:4002
Content-Type: application/json

{
  "jokeId": "6763db7e516a5673ed27f31b",
  "joke": "What do you call a fake noodle? An Impasta!",
  "category": "Dad Jokes"
}

